blueapi:
  hostNetwork: false
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/hostname: bl48p-ea-serv-01.diamond.ac.uk
  tolerations:
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
    - key: beamline
      operator: Equal
      value: bl48p
      effect: NoSchedule
  ingress:
    create: true
    host: p48-blueapi.diamond.ac.uk
  extraEnvVars:
    - name: BEAMLINE
      value: p48
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rabbitmq-password
          key: rabbitmq-password
  tracing:
    otlp:
      enabled: true
      server:
        host: http://jaeger-all-in-one # replace with central instance
  worker:
    env:
      sources:
      - kind: dodal
        module: dodal.beamlines.training_rig
      - kind: planFunctions
        module: htss_rig_bluesky.plans
      - kind: planFunctions
        module: dodal.plans
      - kind: planFunctions
        module: ophyd_async.plan_stubs
      events:
        broadcast_status_events: False
    stomp:
      auth:
        username: p48
        password: ${RABBITMQ_PASSWORD}
      host: p48-rabbitmq
    oidc:
      well_known_url: "https://authn.diamond.ac.uk/realms/master/.well-known/openid-configuration"
      client_id: "blueapi-cli"
    scratch:
      root: /dls_sw/htss/p48/scratch
  
  initContainer:
    scratch:
      root: /dls_sw/htss/p48/scratch
      repositories:
        - name: dodal
          remote_url: https://github.com/DiamondLightSource/dodal.git
        - name: htss-rig-bluesky
          remote_url: https://github.com/DiamondLightSource/htss-rig-bluesky.git
  scratchHostPath: /dls_sw/htss/p48/scratch
